import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mark&#39;s Tech Glossary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline pb-2 text-center">
        Hello world!
      </h1>
      <div className="flex flex-row content-center">
        <Link href="#">A-M</Link>
        <Link href="#">N-Z</Link>
      </div>
    </>
  );
}
